### ISSUE TITLE
training four-bar models

### ISSUE THREAD

**Issue by naotokui** [allenhung1025/loop-generation#3]
Thanks for sharing this great repo! 
One question I have is... how did you train the four-bar model? Every time I tried to train some four-bar models with four-bar-long loops, I always faced mode collapses. I tried smaller learning rates, but it didn't work either. Any tips?

**Comment by allenhung1025** [comment]
Hi @naotokui, 
May I ask how much data you have used in training? From my experience, I have used roughly 6000 four-bar-loop to have a good result.

**Comment by naotokui** [comment]
Sorry, I missed your comment. It turned out... the issue was the small difference between the shape of preprocessed data (80, 641) and the shape of the generated spectrogram (80, 640) in the case of my two-bar model.   Thanks again for your feedback!

**Comment by littlebeanhp** [comment]
> Sorry, I missed your comment. It turned out... the issue was the small difference between the shape of preprocessed data (80, 641) and the shape of the generated spectrogram (80, 640) in the case of my two-bar model. Thanks again for your feedback!

@naotokui Have you successfully trained the 4-bar model, and Is this still the solution? I have trained the 4-bar model and it generates absolute nonsense... The mels are all distorted.
